# Generated by Django 4.1.4 on 2022-12-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authreqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=6)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
