# Generated by Django 4.1.4 on 2022-12-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authreqs',
            name='status',
            field=models.CharField(choices=[('password', 'password'), ('verification code', 'verification code')], max_length=50),
        ),
    ]
